### PR TITLE
README Refactor

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
Please check the **[Preview]**.

### Changes

- Converted raw links into referenced ones
- Simplified syntax

[Preview]: https://github.com/ElectronicsArchiver/Tess/blob/R/README.md?plain=1

### CODE REVIEW

**Comment by SquitchYT** [comment]
Hello @ElectronicsArchiver 
I'm glad that you have refactor the README. However, I find the new rendering worse than the old one. Perhaps you could modify this in order to have the same rendering as the current one

**Comment by ElectronicsArchiver** [comment]
Like this?

**Comment by SquitchYT** [comment]
It's better, maybe without italic and with the first line in bold would be better

**Comment by ElectronicsArchiver** [comment]
The first line of the description is italic & bold so..

**Comment by ElectronicsArchiver** [comment]
I can make the two lines of the description both 
only bold I guess, if that's what you want?

**Comment by SquitchYT** [comment]
I meant **without** the italics

**Comment by SquitchYT** [comment]
and yes, the two lines in bold would be perfect I think

**Comment by SquitchYT** [comment]
It's perfect now, thank you!

**Pull request merged**
